#!/usr/bin/env python3
"""Phase 7 Part 59 — Official User Guide + Testing / UAT Manual (body PDF).

Praveen Garments Billing / POS / Inventory — the client-facing operating manual.
Route: pdf skill Report brief (ReportLab body, HTML cover merged separately).

Numbering plan (Step 3.5):
  cover -> no number | TOC -> no number | content chapters 1..15
"""
import hashlib
import os
import sys

PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, 'scripts'))

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import (
    CondPageBreak, KeepTogether, PageBreak, Paragraph, SimpleDocTemplate,
    Spacer, Table, TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade, seed 7) ━━
PAGE_BG = colors.HexColor('#f1f0ef')
SECTION_BG = colors.HexColor('#f2f1f0')
CARD_BG = colors.HexColor('#e8e7e4')
TABLE_STRIPE = colors.HexColor('#eeedeb')
HEADER_FILL = colors.HexColor('#504933')
COVER_BLOCK = colors.HexColor('#867b5a')
BORDER = colors.HexColor('#cfcab8')
ICON = colors.HexColor('#8c7e52')
ACCENT = colors.HexColor('#87702a')
ACCENT_2 = colors.HexColor('#3a95b4')
TEXT_PRIMARY = colors.HexColor('#1c1c1a')
TEXT_MUTED = colors.HexColor('#78766f')
SEM_SUCCESS = colors.HexColor('#46875c')
SEM_WARNING = colors.HexColor('#a18347')
SEM_ERROR = colors.HexColor('#92453e')
SEM_INFO = colors.HexColor('#466a8e')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT = colors.white
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = TABLE_STRIPE

# ── fonts ──────────────────────────────────────────────────────────────────
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')

from pdf import install_font_fallback  # noqa: E402
install_font_fallback()

# ── layout constants ───────────────────────────────────────────────────────
MARGIN = 0.9 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25

OUT = '/home/z/my-project/scripts/p7-guide-body.pdf'
DOC_TITLE = 'Praveen Garments — Official User Guide + Testing / UAT Manual'

# ── styles ─────────────────────────────────────────────────────────────────
S = {}
S['h1'] = ParagraphStyle('H1', fontName='FreeSerif', fontSize=20, leading=26,
                         textColor=HEADER_FILL, spaceBefore=18, spaceAfter=10)
S['h2'] = ParagraphStyle('H2', fontName='FreeSerif', fontSize=14.5, leading=19,
                         textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=6)
S['h3'] = ParagraphStyle('H3', fontName='FreeSerif', fontSize=11.5, leading=15,
                         textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=5)
S['body'] = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=16.5,
                           textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=8)
S['bullet'] = ParagraphStyle('Bullet', parent=S['body'], leftIndent=16,
                             bulletIndent=4, spaceAfter=4, alignment=TA_LEFT)
S['note'] = ParagraphStyle('Note', fontName='FreeSerif', fontSize=10, leading=15,
                           textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S['tbl_h'] = ParagraphStyle('TblH', fontName='FreeSerif', fontSize=9.5, leading=12.5,
                            textColor=colors.white, alignment=TA_LEFT)
S['tbl_c'] = ParagraphStyle('TblC', fontName='FreeSerif', fontSize=9.5, leading=13,
                            textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap='CJK')
S['caption'] = ParagraphStyle('Caption', fontName='FreeSerif-Italic', fontSize=8.5,
                              leading=11, textColor=TEXT_MUTED, alignment=TA_CENTER,
                              spaceBefore=3, spaceAfter=6)
S['toc0'] = ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=11.5, leading=17,
                           leftIndent=6, textColor=TEXT_PRIMARY)
S['toc1'] = ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=9.5, leading=14,
                           leftIndent=24, textColor=TEXT_MUTED)

# ── doc template with auto-TOC ─────────────────────────────────────────────
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


def _bm(paragraph, text, level):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), paragraph)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def H1(text):
    return [CondPageBreak(H1_ORPHAN), _bm(S['h1'], text, 0),
            Spacer(1, 2)]


def H2(text):
    return [CondPageBreak(60), _bm(S['h2'], text, 1)]


def H3(text):
    return [Paragraph('<b>%s</b>' % text, S['h3'])]


def P(text):
    return Paragraph(text, S['body'])


def BUL(items):
    return [Paragraph('•  %s' % it, S['bullet']) for it in items]


def TBL(headers, rows, ratios, caption=None):
    assert abs(sum(ratios) - 1.0) < 0.01, 'ratios must sum to 1'
    widths = [r * AVAIL_W * 0.98 for r in ratios]
    data = [[Paragraph('<b>%s</b>' % h, S['tbl_h']) for h in headers]]
    for row in rows:
        data.append([Paragraph(str(c), S['tbl_c']) for c in row])
    t = Table(data, colWidths=widths, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i),
                      TABLE_ROW_ODD if i % 2 == 0 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    out = [Spacer(1, 10), t]
    if caption:
        out += [Spacer(1, 2), Paragraph(caption, S['caption'])]
    out.append(Spacer(1, 10))
    return out


def NOTE(title, text, tone=None):
    """Callout box: accent left border + light tint background."""
    box = Table(
        [[Paragraph('<b>%s</b>' % title, S['note'])],
         [Paragraph(text, S['note'])]],
        colWidths=[AVAIL_W * 0.96], hAlign='CENTER')
    box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (0, 0), 8),
        ('BOTTOMPADDING', (0, -1), (-1, -1), 8),
        ('TOPPADDING', (0, 1), (-1, 1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 2),
    ]))
    return [Spacer(1, 8), KeepTogether(box), Spacer(1, 10)]


# ── story ──────────────────────────────────────────────────────────────────
story = []

toc = TableOfContents()
toc.levelStyles = [S['toc0'], S['toc1']]
story.append(Paragraph('<b>Table of Contents</b>', S['h1']))
story.append(Spacer(1, 8))
story.append(toc)
story.append(PageBreak())

# ═════════════════════════════════ CHAPTER 1 ══════════════════════════════
story += H1('1. Getting Started')
story += H2('1.1 What This Software Does')
story.append(P(
    'Praveen Garments Billing / POS / Inventory is the private, single-store business '
    'system that runs the daily shop counter. It covers the complete garment trade '
    'workflow: catalogue with size and colour variants, barcode and QR identification '
    'down to the exact variant, stock tracked per location, fast POS billing with cash, '
    'UPI, card and credit payments, printing of GST invoices, customer and supplier '
    'accounts, purchases and returns, exchanges, day-to-day expenses, and seventeen '
    'management reports with a live dashboard. Every rupee and every unit of stock is '
    'written to a PostgreSQL database protected by row-level security, so the numbers '
    'on the dashboard are the same numbers an auditor would find in the ledger.'))
story.append(P(
    'The system is deliberately private: there is no public sign-up, no self-service '
    'registration, and no data shared with third parties. User accounts are created by '
    'an administrator inside the shop, and every sensitive action is permission-checked '
    'in the database itself, not only hidden in the interface. This guide is the single '
    'official reference for the store team and for anyone testing the system before '
    'acceptance. It is a living document: whenever a feature changes, the relevant '
    'section must be updated in the same release so the manual and the software never '
    'drift apart.'))

story += H2('1.2 System Requirements')
story.append(P(
    'The application is a web system and needs no installation on the billing computer. '
    'Open it in a modern Chromium-based browser (Chrome or Edge, current version). Each '
    'counter station should have a stable internet connection because the database is '
    'hosted online; billing stops safely with an error message if the connection drops, '
    'and it never records a payment it could not finish. Recommended screen width is '
    '1280 px or more for the POS screen, although the layout adapts down to mobile '
    'widths. Optional hardware — a USB barcode scanner, a label printer and a receipt '
    'printer — connects to the same computer and needs no special drivers; see the '
    'Hardware Setup chapter for honest details of what has and has not been physically '
    'tested.'))

story += H2('1.3 Logging In')
story.append(P(
    'Open the shop URL and you will see the sign-in page with the shop name and logo. '
    'Enter the email address and password given by the administrator. If the password '
    'is wrong the page shows a clear inline message; if the account has been '
    'deactivated, the system signs you out with an explanation. After signing in you '
    'land on the Dashboard. Use the account menu at the top right to sign out; the '
    'action is recorded in the audit trail. Password resets are done by an '
    'administrator from the Users page, or through the forgot-password link which '
    'emails a reset link to your registered address.'))

story += H2('1.4 Users, Roles and Permissions')
story.append(P(
    'Every person who uses the system gets one account with one role. The role decides '
    'which pages appear and, more importantly, which operations the database accepts. '
    'Four roles exist: <b>admin</b> (full control including users and settings), '
    '<b>manager</b> (everything commercial — purchases, returns, approvals, reports), '
    '<b>staff</b> (catalogue and stock work, no approvals), and <b>cashier</b> (POS '
    'billing and held bills only). Permission names follow the action, for example '
    'manage_products, manage_inventory, view_reports, manage_expenses.'))
story += TBL(
    ['Capability', 'Admin', 'Manager', 'Staff', 'Cashier'],
    [
        ['Create / edit users and roles', 'Yes', 'No', 'No', 'No'],
        ['Company settings & branches', 'Yes', 'No', 'No', 'No'],
        ['Create products, variants, barcodes', 'Yes', 'Yes', 'Yes', 'No'],
        ['Stock adjustments & transfers', 'Yes', 'Yes', 'Yes', 'No'],
        ['POS billing & held bills', 'Yes', 'Yes', 'Yes', 'Yes'],
        ['Approve expenses, refunds, returns', 'Yes', 'Yes', 'No', 'No'],
        ['Purchases, suppliers, payables', 'Yes', 'Yes', 'No', 'No'],
        ['View reports & audit trail', 'Yes', 'Yes', 'No', 'No'],
    ],
    [0.40, 0.15, 0.15, 0.15, 0.15],
    'Table 1-1 — Role capability matrix (enforced in the database, not just hidden in the UI).')
story.append(P(
    'Hiding a button is not security: the enforcement happens in the database. A '
    'cashier who somehow calls an admin API directly receives an authorization error, '
    'because the permission check runs again server-side inside the transaction. The '
    'role matrix itself is read-only in Settings; changing a role\u2019s permissions is a '
    'database-level change reserved for future phases, and the screen says so honestly.'))

story += H2('1.5 A Quick Tour of the Screens')
story += TBL(
    ['Menu', 'What you do there'],
    [
        ['Dashboard', 'Today\u2019s sales, bills, items sold, payment split, low stock, dues and expenses at a glance.'],
        ['POS', 'The billing counter: scan, search, cart, customer, discount, checkout and print.'],
        ['Sales', 'Bill history, invoice reprint, returns, exchanges and cancellations.'],
        ['Payments', 'Every money movement: sales payments, customer receipts, supplier payments, refunds.'],
        ['Products', 'Catalogue: products, variants, SKU, barcode, QR, images, attributes.'],
        ['Inventory', 'Current stock by variant and location, adjustments, transfers, history, locations.'],
        ['Purchases', 'Purchase orders, supplier invoices (goods receipt), supplier returns.'],
        ['Customers / Suppliers', 'Accounts, statements, outstanding balances, payment history.'],
        ['Expenses', 'Shop spending with categories, receipts and approval flow.'],
        ['Reports', 'Seventeen reports with date filters and CSV export.'],
        ['Settings / Users', 'Company profile, branches, prefixes, business rules, user accounts.'],
    ],
    [0.22, 0.78],
    'Table 1-2 — The main menu in daily-use order.')

# ═════════════════════════════════ CHAPTER 2 ══════════════════════════════
story += H1('2. Dashboard and Reports')
story += H2('2.1 Reading the Dashboard')
story.append(P(
    'The Dashboard opens with a period selector (today, yesterday, this week, this '
    'month, or a custom range). Every card is computed from real transactions in that '
    'period: gross sales, net sales, number of bills, items sold, average bill value, '
    'payment-method split, refunds, expenses, profit estimate, low-stock count and '
    'out-of-stock count. Cards that would be empty show an honest zero — the system '
    'never displays fake or sample data. If the reporting functions are ever not yet '
    'applied on the database, the page says so plainly instead of showing wrong '
    'numbers.'))
story.append(P(
    'Reconciliation habit for the owner: at closing time, compare the payment split '
    'card with the cash drawer count and the UPI statement. The numbers must match to '
    'the rupee because both come from the same sale payments table. If they differ, '
    'use the Payments page to find the transaction that explains the gap before '
    'assuming an error — for example a bill paid half in cash and half by UPI appears '
    'in both columns.'))

story += H2('2.2 Reports Overview')
story.append(P(
    'The Reports page lists seventeen reports, each gated by the view_reports '
    'permission. Every report supports a date range, applies filters only when you '
    'press Apply, and can be exported to CSV (capped at 5,000 rows to protect the '
    'browser). The most used daily reports are Sales, Payments, Cash summary and '
    'Returns; GST and Profit reports are designed for the accountant at month end. '
    'Values shown are recomputed directly from bills, items, payments and purchase '
    'lines — the audit found every report in agreement with the underlying tables.'))
story += TBL(
    ['Report', 'Answers the question'],
    [
        ['Sales', 'How many bills, how much gross/net, tax and discount, per day — filter by payment status.'],
        ['Product sales', 'Which variants sold how many units at what value in the period.'],
        ['Catalog performance', 'Which products move fastest and which sit on the shelf.'],
        ['Payments', 'Money in by method, day by day, including dues collected.'],
        ['Cash', 'Opening float, cash sales, refunds paid, expenses — the drawer story.'],
        ['GST / Tax', 'Taxable value and CGST / SGST / IGST split per rate.'],
        ['Profit', 'Sales margin minus weighted-average purchase cost.'],
        ['Stock valuation', 'What the current stock is worth at cost and at price.'],
        ['Stock performance', 'Turnover and dead stock by variant.'],
        ['Purchase / Supplier', 'Purchases, payables and supplier activity.'],
        ['Customer', 'Top customers, dues and payment behaviour.'],
        ['Expense / Returns', 'Spending by category; returns and refunds.'],
        ['Audit trail', 'Who changed what, when — every sensitive action.'],
    ],
    [0.30, 0.70],
    'Table 2-1 — The seventeen reports (grouped) and their business use.')

# ═════════════════════════════════ CHAPTER 3 ══════════════════════════════
story += H1('3. Product Catalog')
story += H2('3.1 Creating a Product')
story.append(P(
    'Open Products and press New Product. The wizard has five short sections: basics '
    '(name, product code, description, gender, fabric), classification (category, '
    'brand), pricing (MRP and selling price, GST rate, HSN code), and variants. The '
    'product code becomes part of every SKU, so keep it short and stable, for example '
    'SHIRT for shirts. Prices entered at product level act as defaults that each '
    'variant can override — a variant with no price of its own sells at the product '
    'price, and changing the product price later only affects variants that never had '
    'their own price set.'))
story.append(P(
    'Categories can be nested one level (Shirts under Men), brands are flat, and sizes '
    'and colours are shared lists; manage them from Products, then Attributes, where '
    'you can add, rename and deactivate entries without deleting history. Deactivating '
    'an attribute hides it from new variants but leaves old bills untouched.'))

story += H2('3.2 Variants: Size × Colour')
story.append(P(
    'Garments sell by exact variant, so the wizard builds a matrix: pick the sizes and '
    'colours the product comes in and the system creates one variant per combination — '
    'Blue/M, Blue/L, Black/M, Black/L each get their own row. Each variant can carry '
    'its own selling price, MRP, barcode and QR code. Deactivating a variant hides it '
    'from POS search but keeps its sales history; you can reactivate it later. You '
    'cannot delete a variant that has ever moved stock, which protects the ledger; '
    'deactivation is the correct way to retire it.'))

story += H2('3.3 SKU, Barcode and QR — How Identification Works')
story.append(P(
    'Every variant has three identifiers and all three resolve to that exact variant, '
    'never to the parent product and never to a sibling variant. The SKU is built '
    'from the product code plus size and colour (for example PG-SHIRT-BLU-M) and is '
    'unique case-insensitively across the catalogue. The barcode is an EAN-13 number '
    'generated with a valid checksum using the reserved in-store prefix range '
    '20000000–29999999, or you can type your supplier\u2019s barcode if the garment '
    'already carries one. The QR code is a short store-issued text identifier. '
    'Duplicate barcodes and duplicate QR codes across different variants are rejected '
    'by the database, so one scanned code can never mean two products.'))
story += NOTE(
    'Why exactness matters at the counter',
    'A scanned barcode must add the precise variant to the cart — Blue/M, not Blue/L. '
    'The POS scanner endpoint matches the identifier to a single variant row and '
    'replies with that variant\u2019s price, stock and location. Partial matches are '
    'never auto-added: typing a fuzzy product name shows a search list instead, and '
    'only an exact SKU / barcode / QR / product-code match adds directly to the cart.')
story.append(P(
    'Print labels from the Labels page: choose a template size, generate the barcode '
    'and QR images, and print through the browser print dialog on a label printer or '
    'normal printer. Scan one printed label back with the counter scanner before '
    'trusting a whole batch — if it opens the exact variant on the product screen, '
    'the labels are correct.'))

story += H2('3.4 Product Images')
story.append(P(
    'Upload a PNG, JPEG or WebP image up to 2 MB on the product page; SVG is rejected '
    'for safety. The image lives in a private Supabase storage bucket with strict '
    'upload policies, and only users with the manage_products permission can add, '
    'replace or remove it. Replacing keeps the same display position so the catalogue '
    'does not jump around. Invalid files and oversized files are rejected with a clear '
    'message both in the browser and again on the server, so a rejected image never '
    'reaches storage.'))

# ═════════════════════════════════ CHAPTER 4 ══════════════════════════════
story += H1('4. Inventory Management')
story += H2('4.1 Stock Model: Variant × Location')
story.append(P(
    'Stock is tracked per variant per location. A shop typically has one Main store; '
    'you can add a Warehouse or shelf locations from Inventory, then Locations (admin '
    'permission). Selling from the POS deducts the stock of the selected location; '
    'receiving a purchase adds to it. Every change writes an append-only movement row '
    'in a ledger that nobody — not even an admin — can edit or delete from the '
    'interface. The current balance is always the sum of the movements for that '
    'variant and location, and the audit verified this equality across the whole '
    'ledger.'))

story += H2('4.2 Opening Stock, Adjustments and Transfers')
story.append(P(
    'When a product first arrives, record Opening Stock once per variant and location '
    '— the system refuses a second opening for the same pair, because opening twice '
    'would double-count. Daily corrections use Adjust: choose the variant, location, '
    'new quantity or delta, and a reason. Reasons are mandatory for adjustments, '
    'damage and loss, and damage movements never increase sellable stock. Moving goods '
    'between locations uses Transfer, which books a transfer-out and a transfer-in in '
    'one atomic step — both sides appear immediately in the history of both '
    'locations, and a half-done transfer cannot exist.'))
story += TBL(
    ['Movement type', 'Written when', 'Effect'],
    [
        ['OPENING', 'First opening stock of a variant at a location', 'Sets the baseline quantity (once only)'],
        ['PURCHASE', 'Supplier invoice received (full or partial)', 'Stock increases by received quantity'],
        ['SALE', 'POS checkout completes', 'Stock decreases by billed quantity'],
        ['SALES_RETURN', 'Customer returns a garment (resellable)', 'Stock increases back'],
        ['DAMAGE_RETURN', 'Customer returns a damaged garment', 'Not added to sellable stock'],
        ['PURCHASE_RETURN', 'Goods sent back to supplier', 'Stock decreases'],
        ['ADJUSTMENT', 'Manual correction with reason', 'Sets or shifts quantity'],
        ['TRANSFER_OUT / IN', 'Location-to-location move', 'One atomic pair of rows'],
        ['EXCHANGE_OUT / IN', 'Exchange of one variant for another', 'Old stock back in, new stock out'],
    ],
    [0.26, 0.40, 0.34],
    'Table 4-1 — The stock ledger movement types and when they are written.')

story += H2('4.3 Low Stock and Out of Stock')
story.append(P(
    'Set a reorder level per variant (the Inventory page shows a reorder column and a '
    'low-stock badge when quantity falls to or below it). The Dashboard low-stock and '
    'out-of-stock cards use the same thresholds. Selling stops safely at zero: when '
    'the last unit is sold the balance becomes exactly 0, and the next sale attempt '
    'fails with INSUFFICIENT_STOCK — the database guard, not just the interface. '
    'Negative stock can be switched on in Settings only if the owner explicitly '
    'accepts that business rule; by default it is off.'))

story += H2('4.4 Reading Stock History')
story.append(P(
    'The History tab shows the movement ledger in newest-first order with an older / '
    'newer pager that pages through the ledger without ever loading it all at once. '
    'Each row shows the movement type, quantity with sign, resulting balance, the '
    'document that caused it (bill number, purchase invoice, return or exchange '
    'reference), the location and the user. This is the screen an auditor asks for '
    'first: every balance on the Current tab can be traced line by line to its '
    'movements.'))

# ═════════════════════════════════ CHAPTER 5 ══════════════════════════════
story += H1('5. POS — Billing at the Counter')
story += H2('5.1 Starting a Bill')
story.append(P(
    'The POS screen is the daily workhorse. The scan box at the top takes keyboard '
    'input from the barcode scanner or typing. Pressing Enter after a code looks it '
    'up: an exact match on SKU, barcode, QR or product code adds the item straight to '
    'the cart with its price and current stock; anything else runs a product search '
    'listing matches by name. Scanning the same item again raises the cart quantity — '
    'scan three times, quantity three — and the audit verified the database ends with '
    'exactly three units deducted and one sale row, never three sales.'))
story.append(P(
    'Pick the billing location if you run more than one (it defaults to Main). '
    'Adjust quantities with the number controls, remove a line with its remove button, '
    'and clear the whole cart with one action. A bill note can be attached and is '
    'printed on the invoice. Pressing Hold parks the cart as a held bill you can '
    'resume later from the held-bills list; discarding a held bill writes no financial '
    'record at all.'))

story += H2('5.2 Attaching a Customer and Discounts')
story.append(P(
    'Choose an existing customer by searching name or phone, or press new customer to '
    'create one inline with just a name and phone number. A walk-in sale needs no '
    'customer. Line-level discounts can be applied per item, and the cart footer shows '
    'subtotal, discount total, GST and grand total live. GST is computed from each '
    'variant\u2019s rate stored on the bill line, so a mixed cart of 5% and 12% items '
    'splits the tax correctly. Prices and taxes are snapshotted onto the bill at the '
    'moment of sale, so later price changes never rewrite an old invoice.'))

story += H2('5.3 Completing the Sale')
story.append(P(
    'Press Charge to open the checkout dialog. Pick the payment method (Cash, UPI, '
    'Card, Credit as enabled in Settings), enter the amount taken, and for cash see '
    'the change due instantly — a bill of 1,250 paid with 2,000 shows change 750. '
    'Split payment is supported: part cash and part UPI on one bill, each with its own '
    'reference. Press Complete Payment once; the button disables itself while the '
    'request runs, and the database transaction creates the sale, its items, its '
    'payments and the stock deductions together or not at all. A failure mid-way '
    'shows an error and leaves no half-bill behind. On success the invoice opens '
    'ready to print.'))

# ═════════════════════════════════ CHAPTER 6 ══════════════════════════════
story += H1('6. Customers and Credit Accounts')
story += H2('6.1 Customer Records')
story.append(P(
    'The Customers page holds every buyer the shop bills by name. Create a customer '
    'with name and phone (phone is the practical identifier at the counter), and '
    'optionally email, GSTIN for business customers, billing address and state (used '
    'for IGST), and a retail/wholesale type. Search covers name, phone, email and '
    'GSTIN. Editing a customer never rewrites past bills — the invoice keeps the '
    'customer name snapshot taken at sale time, exactly like prices. Deactivating a '
    'customer hides them from POS selection while keeping their full history.'))

story += H2('6.2 Credit Sales and Dues')
story.append(P(
    'A credit sale is simply a bill paid partly or fully by the Credit method: pay '
    '2,000 on a 5,000 bill and the customer\u2019s due becomes 3,000. Dues live on the '
    'bill, not on a guessed balance field — the customer\u2019s outstanding is always '
    'the sum of unpaid bill portions, minus credits from returns and payments, and '
    'the audit reconciled this sum to the rupee for every test account. The '
    'Customers page shows each account\u2019s current dues; the dashboard pending-'
    'payments card aggregates the same figure for the whole book.'))

story += H2('6.3 Receiving Payments and Statements')
story.append(P(
    'Open the customer\u2019s page and press Record Payment to take money against dues. '
    'The payment is allocated to outstanding bills oldest-first (FIFO), prints a '
    'receipt with its own CR number, and appears on the Payments page. Paying 1,000 '
    'of the 3,000 due leaves 2,000 — check it on the statement. Press Statement to '
    'see the full ledger for any date range: bills, till payments, receipts, return '
    'credits and cancellations, each with a running balance, ending on the same due '
    'figure the customer page shows. If the two ever disagree, trust the statement '
    'and report it — the audit found no such disagreement on any account.'))

# ═════════════════════════════════ CHAPTER 7 ══════════════════════════════
story += H1('7. Checkout and Payment Methods')
story += H2('7.1 Method Rules')
story += TBL(
    ['Method', 'Works like', 'Watch out for'],
    [
        ['Cash', 'Money in the drawer; change is computed for you', 'Count the change shown on screen, it is exact'],
        ['UPI', 'Digital transfer; optional reference note', 'Confirm the UPI app credited before completing'],
        ['Card', 'Swipe / tap on the EDC machine; optional reference', 'The bank slip number is handy as the reference'],
        ['Credit', 'Dues recorded on the customer\u2019s account', 'Only works when a customer is attached to the bill'],
        ['Split', 'Any two methods on one bill', 'Total of parts must equal the bill total'],
    ],
    [0.16, 0.44, 0.40],
    'Table 7-1 — Payment methods and their rules.')
story.append(P(
    'The checkout refuses impossible math: the parts of a split payment must sum to '
    'the bill total, credit is rejected without a customer, and change is only shown '
    'for cash. Every payment row stores its method, amount and optional reference, '
    'so the Payments report can reconstruct the day exactly as the drawer and bank '
    'statements saw it.'))

story += H2('7.2 Idempotency — Why Double-Clicks Are Safe')
story.append(P(
    'The Complete Payment button disables itself the moment it is pressed and stays '
    'disabled until the server replies. Behind the scenes the checkout is one atomic '
    'database transaction: sale, items, payments and stock movements commit together '
    'or roll back together. Rapid double-clicks therefore cannot create two bills — '
    'the audit hammered this path with parallel requests and the ledger stayed '
    'consistent: one bill, one payment set, one deduction set, always. If the network '
    'drops mid-payment the screen shows an error, nothing is recorded, and the cart '
    'is still there to retry.'))

# ═════════════════════════════════ CHAPTER 8 ══════════════════════════════
story += H1('8. Invoices and Printing')
story += H2('8.1 What Is On the Invoice')
story.append(P(
    'Each completed bill gets the next invoice number from your configured prefix '
    '(for example INV-2026-000123 — the prefix and year are set in Settings). The '
    'invoice prints the company name, logo, address and GSTIN from Settings, the '
    'invoice number, date and time, cashier name, customer name and phone when '
    'attached, and for every line: product, size and colour, SKU, quantity, MRP, unit '
    'price, discount, GST rate and amount, and line total. The footer shows subtotal, '
    'discount, tax and grand total, the payments received with methods and '
    'references, change given for cash, dues for credit, and the bill note if any. '
    'All values are snapshots — a price change tomorrow does not move yesterday\u2019s '
    'invoice.'))
story += NOTE(
    'A4 and thermal printing',
    'Printing uses the browser print dialog. For A4 the layout fits a standard sheet '
    'with margins; for thermal receipt printers choose the printer\u2019s paper size in '
    'the browser print dialog. Direct ESC/POS printer integration is NOT implemented '
    '— printing goes through the browser, which works reliably but is a browser '
    'print, not a printer driver integration. Say it honestly: browser printing '
    'verified; direct thermal integration not implemented.')

story += H2('8.2 Reprints and History')
story.append(P(
    'Open Sales, find the bill (search by invoice number, customer or cashier), and '
    'press print to reprint the same invoice document. A reprint is identical to the '
    'original — same number, same values — and creates no new financial record. '
    'Cancelling a bill (manager permission) asks for a reason, marks the bill '
    'CANCELLED, puts sold stock back, and records the action in the audit trail; '
    'cancelled bills are excluded from sales totals but remain visible in history so '
    'the number sequence stays explainable.'))

# ═════════════════════════════════ CHAPTER 9 ══════════════════════════════
story += H1('9. Purchases, Suppliers and Stock-In')
story += H2('9.1 Suppliers and Purchase Orders')
story.append(P(
    'Suppliers are created with name and phone, optionally GSTIN, address and payment '
    'terms. A Purchase Order records what you intend to buy — supplier, location, '
    'expected date and lines with variant, quantity and unit cost — and gets the next '
    'PO number from your prefix. A PO is just intent: it moves no stock and owes '
    'nothing until you receive against it. Purchase history, payables and payments '
    'per supplier live on the supplier\u2019s page.'))

story += H2('9.2 Receiving Goods — the Purchase Invoice')
story.append(P(
    'Receiving is the money step: press Receive Goods / Purchase Invoice from the '
    'Purchases page. Link the purchase order to pre-fill its pending lines, or leave '
    'it unlinked for a direct purchase. Enter the supplier\u2019s invoice number and '
    'date as printed on their bill. For a linked order the received quantity of each '
    'line is capped at what remains pending — ordered 100, already received 60, and '
    'the next delivery can receive at most 40; receiving 60 adds exactly 60 to stock, '
    'never 100. When you press Receive goods, one atomic transaction books the stock '
    'in, creates the payable to the supplier, and advances the linked PO — there is '
    'no half-received state. Uncheck Receive goods now to save a draft that touches '
    'nothing until confirmed.'))
story += NOTE(
    'Partial receiving rule',
    'Ordered = 100, received = 60 means stock +60 and 40 still pending on the order. '
    'The audit verified the database enforces this cap line by line, so over-'
    'receiving a linked order is impossible through the interface.')

story += H2('9.3 Supplier Payments and Returns')
story.append(P(
    'Pay a supplier from their page with Record Payment; payables are the sum of '
    'unpaid invoice amounts, oldest invoices settled first. A Purchase Return sends '
    'goods back to the supplier: choose the invoice, return up to the received '
    'quantity per line, and the system reduces stock, writes the movement, reduces '
    'the payable, and refuses to return more than you actually received. Returns '
    'cannot exceed eligible quantity — the guard is in the database.'))

# ═════════════════════════════════ CHAPTER 10 ═════════════════════════════
story += H1('10. Sales Operations — Returns, Exchanges, Refunds')
story += H2('10.1 Sales Return')
story.append(P(
    'A customer brings back a garment: open the bill from Sales and press Return. '
    'Each line shows the eligible quantity (bought minus already returned). Return '
    'one of three sold and the net effect is exactly minus two on that variant\u2019s '
    'stock — one SALE row of -3 and one SALES_RETURN row of +1 in the ledger. For a '
    'resellable garment the stock comes back as sellable; mark the return as damaged '
    'instead and the unit does NOT re-enter sellable stock, it is written off the '
    'sellable balance as damaged. The refund choice mirrors how the customer is '
    'compensated: cash out of the drawer (recorded as a refund payment), UPI back, or '
    'credit onto the customer\u2019s account which reduces their dues.'))
story += NOTE(
    'Verified arithmetic',
    'Sell 3, return 1 (resellable): ledger shows SALE -3 and SALES_RETURN +1, net '
    'stock -2, refund recorded once. Damaged returns never inflate sellable stock. '
    'Both behaviours are enforced by the database engine and were re-verified in the '
    'Phase 7 regression.')

story += H2('10.2 Exchange')
story.append(P(
    'An exchange swaps one variant for another on the same bill. Old garment 999, '
    'new garment 1,199: the customer pays the 200 difference through any payment '
    'method; new cheaper (1,199 old, 999 new) and the system refunds the 200 the '
    'same way. Stock follows the swap — old variant back in, new variant out — and '
    'the exchange document records both sides, the price difference and the payment, '
    'with its own EX number. The Payments and Cash reports include exchange '
    'collections and exchange cash-out so the drawer still reconciles at closing.'))
story.append(P(
    'Refunds always attach to a return or an exchange document — there is no '
    'free-floating refund, so money out of the drawer is always explainable by a '
    'document a manager can open.'))

# ═════════════════════════════════ CHAPTER 11 ═════════════════════════════
story += H1('11. Expenses')
story += H2('11.1 Recording Shop Spending')
story.append(P(
    'Cashiers never see this module; it needs the manage_expenses permission. Record '
    'an expense with category (manage the category list from the page — Rent, '
    'Electricity, Tea, and so on, configurable, never hardcoded), description, '
    'amount, payment method, date and optional branch. When you save, the expense '
    'sits in a pending state until an approver reviews it — this mirrors how real '
    'shops control petty spending. Approving finalises it into the reports; '
    'cancelling (with reason) removes it from totals but keeps it visible in '
    'history with the cancellation reason, so the audit trail explains every '
    'number the Cash and Expense reports show.'))
story += H2('11.2 Receipts and Attachments')
story.append(P(
    'Attach the physical receipt as a photo or PDF: PNG, JPEG, WebP or PDF up to '
    '5 MB, validated in the browser and again on the server, stored in a private '
    'bucket that only expense-approvers can read. If the attachment upload fails '
    'after the expense saved, the system says so honestly — the expense is saved '
    'and the receipt can be re-attached from the expense detail. The Cash report '
    'subtracts approved expenses from cash, so the drawer story stays complete.'))

# ═════════════════════════════════ CHAPTER 12 ═════════════════════════════
story += H1('12. Settings and Security')
story += H2('12.1 Settings That Change Behaviour')
story.append(P(
    'Settings are grouped into Company (name, logo, address, GSTIN, currency '
    'display, timezone), Branches, and business-rule tabs. Every value is stored '
    'in the database — nothing about your shop is baked into the code — and a '
    'saved setting changes real behaviour, not just the screen: invoice prefixes '
    'feed the numbering, low-stock thresholds drive the dashboard badges, and the '
    'payment-methods list controls which buttons the checkout offers. After '
    'changing anything, save, refresh and check the behaviour in the relevant '
    'module — that is exactly what the Phase 7 regression re-tested.'))
story += TBL(
    ['Setting', 'Where it bites'],
    [
        ['Company profile & logo', 'Login page, printed invoices, headers everywhere'],
        ['Invoice / document prefixes', 'INV, PO, PI, PR, SR, EX, EXP, CR, SP numbers'],
        ['Payment methods list', 'Which methods the checkout and expense forms offer'],
        ['Low stock threshold', 'Dashboard low-stock card and Inventory badges'],
        ['Allow negative stock', 'Whether the last unit can be oversold (default off)'],
        ['Return window (days)', 'How old a bill may be for returns and exchanges'],
        ['Tax settings', 'GST rates offered on products and GST report grouping'],
    ],
    [0.34, 0.66],
    'Table 12-1 — Key settings and where they change behaviour.')

story += H2('12.2 Security Model in Plain Words')
story.append(P(
    'All data lives in Supabase PostgreSQL with row-level security (RLS) on every '
    'table. In practice this means: signed-in users only ever see rows their role '
    'permits, writes go through stored functions that check permission again '
    'inside the transaction, the append-only stock ledger cannot be edited by '
    'anyone including admins, and the anonymous public key can read nothing of '
    'your business data. The audit tried direct table access, forged requests and '
    'wrong-role operations — the database refused them all. Two operational rules '
    'keep this true: public sign-up must stay disabled at the Supabase project '
    'level (new staff are created by your admin), and the service-role key must '
    'never leave the server configuration.'))

# ═════════════════════════════════ CHAPTER 13 ═════════════════════════════
story += H1('13. Hardware Setup — Honest Status')
story += H2('13.1 What Has Been Verified and How')
story.append(P(
    'This section separates three levels of truth: <b>software-verified</b> (the '
    'workflow works through the interface), <b>physically verified</b> (tested '
    'with the actual device), and <b>not tested</b>. The audit ran all software '
    'workflows against the live database; no physical scanner, label printer or '
    'mobile device was attached to the audit environment, so this manual claims '
    'physical compatibility only where the interface design guarantees it and '
    'labels everything else clearly. Never let documentation claim more than was '
    'tested.'))
story += TBL(
    ['Device', 'Status', 'What this means for you'],
    [
        ['USB / Bluetooth keyboard-wedge barcode scanner', 'SOFTWARE VERIFIED (not physically tested)', 'Scanners that type characters + Enter work by design; plug in and scan into the POS box, then run the 5-minute check below'],
        ['2D QR scanner (keyboard-wedge mode)', 'SOFTWARE VERIFIED (not physically tested)', 'Same as above: it must be in keyboard (HID) mode, not serial mode'],
        ['Mobile camera QR scanning', 'IMPLEMENTED, not physically tested', 'Requires HTTPS and camera permission; message explains fallbacks when unsupported'],
        ['Receipt / label printing', 'BROWSER PRINT verified', 'Print via the browser dialog on any installed printer; no direct ESC/POS integration'],
        ['Cash drawer (automatic open)', 'NOT IMPLEMENTED', 'The drawer is opened manually with the key; nothing in the software triggers it'],
    ],
    [0.30, 0.26, 0.44],
    'Table 13-1 — Hardware status: software-verified vs physically-verified vs not tested.')

story += H2('13.2 Installing a Barcode Scanner (5 Minutes)')
story += BUL([
    'Plug the USB scanner into the billing computer (or pair it over Bluetooth) and let it install as a keyboard — no driver needed.',
    'Open the POS page and click once in the scan box so it has focus.',
    'Scan any garment label: the code should appear in the box and press Enter automatically (most scanners send Enter after the code; if not, configure the scanner\u2019s "Enter suffix / carriage return" option per its manual).',
    'The exact variant must appear in the cart — if a different size or colour appears, stop and check that label; report it before billing.',
    'Scan the same item twice: quantity becomes 2. That is the correct behaviour.',
])
story.append(P(
    'Focus note: the scan box keeps focus after each successful add, so continuous '
    'scanning works without touching the mouse. If you click elsewhere the scan '
    'goes nowhere — click back into the box and the first scan after that lands '
    'normally. This is standard keyboard-wedge behaviour, not a fault.'))

story += H2('13.3 Mobile Camera QR')
story.append(P(
    'On a phone, open the POS page over HTTPS and the camera-scan button becomes '
    'available; it asks for camera permission and then scans QR labels live. If '
    'the browser reports that camera scanning is not supported, the message '
    'explains the two usual causes — the site is not on HTTPS, or the browser '
    'lacks the BarcodeDetector capability — and points to the fallbacks, which '
    'always work: type or paste the QR text into the scan box, use product '
    'search, or use the USB scanner. No physical phone test was performed by the '
    'audit, so treat mobile camera scanning as implemented-but-unverified until '
    'you try one bill on the shop phone.'))

story += H2('13.4 Printers and the Cash Drawer')
story.append(P(
    'Install any Windows printer as usual and choose it in the browser print '
    'dialog when printing invoices or labels; thermal receipt printers work with '
    'their own paper size selected in the same dialog. There is no direct '
    'ESC/POS or network-printer integration in this version — that is a future '
    'feature, listed honestly in the recommendations chapter. The cash drawer is '
    'not connected to the software at all: open it manually when giving change, '
    'and reconcile it with the Cash report at closing.'))

# ═════════════════════════════════ CHAPTER 14 ═════════════════════════════
story += H1('14. Troubleshooting and Common Errors')
story += TBL(
    ['Symptom', 'Meaning', 'What to do'],
    [
        ['"INSUFFICIENT_STOCK" when billing', 'The last unit was sold moments ago by another counter', 'Refresh the cart; the stock guard protected both bills — exactly one sale went through'],
        ['Login says account disabled', 'An administrator deactivated the account', 'Ask the admin to reactivate it from Users'],
        ['Page shows "Something went wrong"', 'An unexpected error — the page stopped rather than showing wrong numbers', 'Reload the page; if it repeats, note what you clicked and tell the administrator (after the Phase 7 fix the known dropdown crash is gone)'],
        ['Scan adds nothing', 'Scanner focus lost, or code has no Enter suffix', 'Click into the scan box; configure the scanner Enter suffix'],
        ['Camera QR says not supported', 'Not HTTPS, or browser lacks BarcodeDetector', 'Use the HTTPS link, update the browser, or use manual entry / search'],
        ['Image upload rejected', 'Not PNG/JPEG/WebP or over 2 MB', 'Convert or shrink the photo and retry'],
        ['Report will not load', 'Migration not applied or filter too narrow', 'Check the setup notice on the page; widen the date range'],
        ['Checkout says network error', 'Connection dropped mid-payment', 'Nothing was charged — check Sales to confirm, then retry the bill'],
    ],
    [0.26, 0.34, 0.40],
    'Table 14-1 — First-line troubleshooting.')
story.append(P(
    'Golden rule: the system never records a payment it cannot finish. If any '
    'error appears during money steps, verify on the Sales or Payments page what '
    'actually landed, then retry. Partial writes are blocked by design — the '
    'audit verified transaction atomicity under deliberate failure injection.'))

# ═════════════════════════════════ CHAPTER 15 ═════════════════════════════
story += H1('15. Tester / UAT and Production Acceptance')
story += H2('15.1 How To Run a UAT Session')
story.append(P(
    'Test with a small, real batch of garments and a second person playing '
    'customer. Use statuses honestly: PASS, FAIL, PARTIAL, BLOCKED, NOT TESTED — '
    'never "looks fine". For every test write down what you did, what you '
    'expected, what actually happened, and the evidence (invoice number, '
    'movement row, report figure). The stock arithmetic tests below are the '
    'heart of acceptance: the database, not the screen, is the judge.'))
story += H2('15.2 Core UAT Checklist')
story += TBL(
    ['#', 'Test', 'Expected result'],
    [
        ['1', 'Create product with 4 variants (Blue M/L, Black M/L), barcodes + QR', 'All four variants listed; each identifier resolves to its exact variant'],
        ['2', 'Set opening stock 10 on Blue M; sell 1 over POS', 'Database stock 9; ledger row SALE -1 referencing the bill'],
        ['3', 'Scan same barcode 3 times, complete sale', 'Cart quantity 3; stock -3 exactly; one bill, one payment set'],
        ['4', 'Sell 1 each of Blue M / Blue L / Black M', 'Each variant -1; no other balance changes'],
        ['5', 'Sell with stock 0', 'Blocked with INSUFFICIENT_STOCK; no negative stock, no invoice'],
        ['6', 'Two bills for the same last unit at once', 'Exactly one succeeds; other fails cleanly; stock ends 0'],
        ['7', 'Rapid double-click Complete Payment', 'One sale, one invoice, one payment, one deduction'],
        ['8', 'Cash 2,000 on a 1,250 bill', 'Change 750 on screen and printed invoice'],
        ['9', 'Split 1,000 cash + 1,500 UPI on 2,500', 'Paid 2,500, due 0; two payment rows with methods'],
        ['10', 'Credit sale 5,000, pay 2,000', 'Customer due 3,000; pay 1,000 more later, due 2,000; statement closing matches'],
        ['11', 'Purchase order 100, receive 60', 'Stock +60; order shows 40 pending; payable = invoice value'],
        ['12', 'Return 3 of a 3-sold item as 1 resellable', 'Net stock -2; refund recorded once; damaged return adds no sellable stock'],
        ['13', 'Exchange 999 item for 1,199 item', 'Customer pays 200; old stock back, new stock out; EX document present'],
        ['14', 'Sell at 999, change price to 1,199', 'Old invoice still prints 999 with its snapshots'],
        ['15', 'Cashier tries Reports / Users / Expenses URLs', 'Permission denied — database-level, not just hidden buttons'],
        ['16', 'Record expense with receipt, approve it', 'Pending then approved; appears in Expense and Cash reports'],
        ['17', 'Change invoice prefix in Settings', 'Next bill uses the new prefix; old numbers unchanged'],
        ['18', 'Full store-day simulation (Part 56 of the audit)', 'Dashboard, reports, drawer and ledger all reconcile'],
    ],
    [0.06, 0.44, 0.50],
    'Table 15-1 — The 18 core UAT checks (statuses: PASS / FAIL / PARTIAL / BLOCKED / NOT TESTED).')

story += H2('15.3 Production Acceptance Checklist')
story += BUL([
    'All 18 core UAT checks above marked PASS by the client, with evidence recorded.',
    'At least one full real day run side-by-side with the old billing method, reconciled to the rupee.',
    'Barcode scanner physically installed and the 5-minute scan check passed on the billing computer.',
    'One printed invoice and one printed label inspected for company name, GSTIN, values and code legibility.',
    'Backup and recovery reviewed with whoever hosts the database (see 15.4) and a restore actually practised once.',
    'Admin password stored safely; service key rotation completed; public sign-up confirmed disabled.',
    'This manual handed to every counter user with a 30-minute walkthrough of POS, returns and end-of-day.',
])

story += H2('15.4 Backup and Recovery Guidance')
story.append(P(
    'The database is the business record, so protect it in three layers. First, '
    'enable automated daily backups on the hosted database (Supabase paid tier '
    'includes point-in-time recovery; verify the retention window covers your '
    'comfort). Second, take a weekly manual export of key tables — sales, sale '
    'items, payments, stock movements, customers, suppliers, purchases, expenses '
    '— as CSV from the Reports exports and store a copy off the shop premises. '
    'Third, practise restoring: a backup that has never been restored is a hope, '
    'not a backup. Recovery expectations to write down with your host: how far '
    'back point-in-time recovery reaches, and how long a full restore takes. The '
    'append-only stock ledger means partial recovery keeps the movement history '
    'trustworthy even if it must be re-summed.'))

story += H2('15.5 Keeping This Manual Alive')
story.append(P(
    'This is a living document. Whenever a feature is added or changed, update '
    'its section in the same release: what it does, the user steps, the '
    'permission that gates it, any new setting, the error handling, the tester '
    'procedure with positive and negative cases, security notes, responsive '
    'behaviour, and hardware implications. A feature that ships without its '
    'manual entry is not finished. Future recommendations currently parked (not '
    'promised): Excel/CSV product import, bulk label printing, direct thermal '
    'printing, cash-drawer integration, opening/closing cash register sessions, '
    'approval limits for discounts, low-stock notifications, and GST accounting '
    'export — the full classified list lives in the Phase 7 audit report.'))

# ── build ──────────────────────────────────────────────────────────────────
def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.drawString(MARGIN, 0.5 * inch, 'Praveen Garments · Version 1.0 · September 2026')
    canvas.drawRightString(PAGE_W - MARGIN, 0.5 * inch, 'Page %d' % doc.page)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.restoreState()


doc = TocDocTemplate(
    OUT, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN, bottomMargin=MARGIN,
    title=DOC_TITLE, author='Z.ai', creator='Z.ai',
    subject='Official user guide and UAT manual for the Praveen Garments POS system',
)
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print('BUILT body:', OUT)

