#!/usr/bin/env python3
"""
Praveen Garments POS — Phase 6 Deep Production Audit — FINAL REPORT (body PDF).

Chapter numbering plan (Step 3.5, cover/TOC unnumbered, body starts at Chapter 1):
  cover -> (HTML/Playwright, merged as page 0)      [no number]
  toc   -> Table of Contents                        [no number]
  1  Executive Summary & Production Verdict
  2  Audit Scope, Method & Evidence Base
  3  System Architecture & the Billing Chain
  4  Migration Integrity (0001-0014)
  5  Page-by-Page Audit Matrix
  6  Identifier & POS Scan Verification
  7  Stock Arithmetic, Concurrency & Idempotency
  8  Payments, Credit & Money-Flow (incl. 0014)
  9  Purchases, Returns, Exchanges & Price History
  10 Dashboard, Reports & End-of-Day Reconciliation
  11 Security & Access Control Audit
  12 Database Integrity Audit
  13 Performance & Scale Readiness
  14 Hardware & Mobile - Honest Status
  15 Browser, Console & Responsive Audit
  16 Workspace Recovery & Environment State
  17 Findings & Fixes Register (P0-P3)
  18 Test Matrix & Coverage Summary
  19 Outstanding Items & Operator Checklist
  20 Final Recommendation & Sign-Off
"""
import hashlib
import os
import sys

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak, HRFlowable, KeepTogether, PageBreak, Paragraph,
    SimpleDocTemplate, Spacer, Table, TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents

PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, "scripts"))
from pdf import install_font_fallback  # noqa: E402

OUT = "/home/z/my-project/download/phase6-body.pdf"

# ---------------------------------------------------------------- fonts ----
FONT_DIR = "/usr/share/fonts"
pdfmetrics.registerFont(TTFont("NotoSerifSC", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf"))
pdfmetrics.registerFont(TTFont("NotoSerifSC-Bold", f"{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf"))
# NOTE: Noto Sans SC static weights are absent in this environment (variable
# font only, unusable by ReportLab) - NotoSerifSC is the CJK fallback instead.
pdfmetrics.registerFont(TTFont("FreeSerif", f"{FONT_DIR}/truetype/freefont/FreeSerif.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Bold", f"{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-Italic", f"{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf"))
pdfmetrics.registerFont(TTFont("FreeSerif-BoldItalic", f"{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf"))
pdfmetrics.registerFont(TTFont("DejaVuSans", f"{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf"))
registerFontFamily("NotoSerifSC", normal="NotoSerifSC", bold="NotoSerifSC-Bold")

registerFontFamily("FreeSerif", normal="FreeSerif", bold="FreeSerif-Bold",
                   italic="FreeSerif-Italic", boldItalic="FreeSerif-BoldItalic")
registerFontFamily("DejaVuSans", normal="DejaVuSans", bold="DejaVuSans")
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
# XL tier: backgrounds (area > 50%, S <= 0.08)
PAGE_BG       = colors.HexColor('#f2f2f0')
SECTION_BG    = colors.HexColor('#eaeae8')
# L tier: surfaces (area 20-50%, S <= 0.15)
CARD_BG       = colors.HexColor('#f1f0ed')
TABLE_STRIPE  = colors.HexColor('#f0f0ee')
# M tier: structural fills (area 5-20%, S <= 0.30)
HEADER_FILL   = colors.HexColor('#5a5238')
COVER_BLOCK   = colors.HexColor('#7b7257')
# S tier: edges & icons (area 1-5%, S <= 0.50)
BORDER        = colors.HexColor('#c2bdb0')
ICON          = colors.HexColor('#77693d')
# XS tier: emphasis (area < 1%, S <= 0.75)
ACCENT        = colors.HexColor('#887129')
ACCENT_2      = colors.HexColor('#7962bd')
# Typography
TEXT_PRIMARY  = colors.HexColor('#21201e')
TEXT_MUTED    = colors.HexColor('#79766f')
# Semantic (muted)
SEM_SUCCESS   = colors.HexColor('#4c875f')
SEM_WARNING   = colors.HexColor('#a2864e')
SEM_ERROR     = colors.HexColor('#864a45')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ------------------------------------------------------------- geometry ----
PAGE_W, PAGE_H = A4
MARGIN = 0.8 * inch                     # symmetric left == right
AVAIL_W = PAGE_W - 2 * MARGIN           # ~480pt
AVAIL_H = PAGE_H - 2 * MARGIN
H1_COND = AVAIL_H * 0.25                # orphan-prevention threshold
MAX_KEEP_HEIGHT = PAGE_H * 0.4

DOC_TITLE = "Praveen Garments POS - Phase 6 Production Audit - Final Report"

# --------------------------------------------------------------- styles ----
S = {}
S["body"] = ParagraphStyle("Body", fontName="FreeSerif", fontSize=10.5, leading=17,
                           alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                           spaceBefore=0, spaceAfter=10)
S["lead"] = ParagraphStyle("Lead", parent=S["body"], fontSize=11, leading=18)
S["h1"] = ParagraphStyle("H1", fontName="FreeSerif", fontSize=22, leading=27,
                         textColor=HEADER_FILL, spaceBefore=0, spaceAfter=0)
S["h2"] = ParagraphStyle("H2", fontName="FreeSerif", fontSize=15, leading=20,
                         textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=7)
S["h3"] = ParagraphStyle("H3", fontName="FreeSerif", fontSize=11.5, leading=16,
                         textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=5)
S["bullet"] = ParagraphStyle("Bullet", parent=S["body"], alignment=TA_LEFT,
                             leftIndent=14, bulletIndent=2, spaceAfter=5)
S["caption"] = ParagraphStyle("Caption", fontName="FreeSerif", fontSize=8.5, leading=12,
                              textColor=TEXT_MUTED, alignment=TA_CENTER,
                              spaceBefore=3, spaceAfter=6)
S["th"] = ParagraphStyle("TH", fontName="FreeSerif", fontSize=9.5, leading=12.5,
                         textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER)
S["td"] = ParagraphStyle("TD", fontName="FreeSerif", fontSize=9, leading=12,
                         textColor=TEXT_PRIMARY, alignment=TA_LEFT)
S["tdc"] = ParagraphStyle("TDC", parent=S["td"], alignment=TA_CENTER)
S["tdb"] = ParagraphStyle("TDB", parent=S["td"], fontName="FreeSerif")
S["stat"] = ParagraphStyle("Stat", fontName="FreeSerif", fontSize=21, leading=25,
                           textColor=ACCENT, alignment=TA_CENTER)
S["statlabel"] = ParagraphStyle("StatLabel", fontName="FreeSerif", fontSize=8.5,
                                leading=11.5, textColor=TEXT_MUTED, alignment=TA_CENTER)
S["toc0"] = ParagraphStyle("TOC0", fontName="FreeSerif", fontSize=11, leading=17,
                           leftIndent=0, textColor=TEXT_PRIMARY)
S["toctitle"] = ParagraphStyle("TOCTitle", fontName="FreeSerif", fontSize=20, leading=25,
                               textColor=HEADER_FILL, spaceAfter=14)

# -------------------------------------------------------------- helpers ----
def para(text, style="body"):
    return Paragraph(text, S[style])

def add_heading(text, style, level=0):
    key = "h_%s" % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def safe_keep_together(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(AVAIL_W, PAGE_H)
        total_h += h
    if total_h <= MAX_KEEP_HEIGHT:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def chapter(num, title, first_block):
    """H1 chapter opener: conditional break + heading + accent rule + first block."""
    h = add_heading("%d. %s" % (num, title), S["h1"], level=0)
    rule = HRFlowable(width="100%", color=ACCENT, thickness=1.6,
                      spaceBefore=5, spaceAfter=12)
    return [CondPageBreak(H1_COND)] + safe_keep_together([h, rule, first_block])

def make_table(headers, rows, ratios, aligns=None, header_style=None, zebra=True):
    """Overflow-safe table: every cell a Paragraph, widths sum to AVAIL_W."""
    n = len(headers)
    assert abs(sum(ratios) - 1.0) < 0.001, "ratios must sum to 1"
    col_widths = [r * AVAIL_W for r in ratios]
    assert sum(col_widths) <= AVAIL_W + 0.5
    aligns = aligns or (["l"] * n)
    data = [[Paragraph("<b>%s</b>" % h, header_style or S["th"]) for h in headers]]
    for row in rows:
        cells = []
        for i, cell in enumerate(row):
            st = S["tdc"] if aligns[i] == "c" else S["td"]
            cells.append(Paragraph(str(cell), st))
        data.append(cells)
    t = Table(data, colWidths=col_widths, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ("TEXTCOLOR", (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 7),
        ("RIGHTPADDING", (0, 0), (-1, -1), 7),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]
    if zebra:
        for r in range(1, len(data)):
            style.append(("BACKGROUND", (0, r), (-1, r),
                          TABLE_ROW_ODD if r % 2 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    return t

def table_block(title_text, tbl, caption_text):
    """Spacer 18 + (title + table kept if short) + Spacer 6 + caption + Spacer 18."""
    out = [Spacer(1, 16)]
    title = para("<b>%s</b>" % title_text, "h3") if title_text else None
    if title is not None:
        out.extend(safe_keep_together([title, tbl]))
    else:
        out.append(tbl)
    out.append(Spacer(1, 6))
    if caption_text:
        out.append(para(caption_text, "caption"))
    out.append(Spacer(1, 14))
    return out

def callout_row(stats):
    """Row of stat callout boxes: [(value, label), ...] 2-4 items."""
    gap = 10
    box_w = (AVAIL_W - gap * (len(stats) - 1)) / len(stats)
    boxes = []
    for value, label in stats:
        inner = Table(
            [[Paragraph("<b>%s</b>" % value, S["stat"])],
             [Paragraph(label, S["statlabel"])]],
            colWidths=[box_w - 2],
        )
        inner.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
            ("BOX", (0, 0), (-1, -1), 1, ACCENT),
            ("TOPPADDING", (0, 0), (-1, 0), 9),
            ("BOTTOMPADDING", (0, -1), (-1, -1), 9),
            ("TOPPADDING", (0, 1), (-1, 1), 2),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        boxes.append(inner)
    outer = Table([boxes], colWidths=[box_w] * len(stats), hAlign="CENTER")
    outer.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))
    return [Spacer(1, 6), outer, Spacer(1, 12)]

def bullets(items):
    return [Paragraph(i, S["bullet"], bulletText="\u2022") for i in items]

# ------------------------------------------------------- doc template ----
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, "bookmark_name"):
            level = getattr(flowable, "bookmark_level", 0)
            text = getattr(flowable, "bookmark_text", "")
            key = getattr(flowable, "bookmark_key", "")
            self.notify("TOCEntry", (level, text, self.page, key))

def on_page(canvas, doc):
    canvas.saveState()
    # header: doc title (left, muted) + accent rule
    canvas.setFont("FreeSerif-Italic", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.52 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.60 * inch, PAGE_W - MARGIN, PAGE_H - 0.60 * inch)
    # footer: author left, bare page number right, light rule above
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont("FreeSerif", 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, "Praveen Garments · Private deployment")
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, str(canvas.getPageNumber()))
    canvas.restoreState()

doc = TocDocTemplate(
    OUT, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=0.95 * inch, bottomMargin=0.85 * inch,
    title=DOC_TITLE, author="Z.ai", creator="Z.ai",
    subject="Phase 6 deep end-to-end production audit of the Praveen Garments POS system",
)

story = []

# ------------------------------------------------------------------ TOC ----
story.append(Paragraph("<b>Table of Contents</b>", S["toctitle"]))
toc = TableOfContents()
toc.levelStyles = [S["toc0"]]
story.append(toc)
story.append(PageBreak())

# ------------------------------------------------- 1. executive summary ----
story.extend(chapter(1, "Executive Summary & Production Verdict", para(
    "This report closes Phase 6, the deep end-to-end production audit of the "
    "Praveen Garments billing, POS and inventory system. The audit examined the "
    "complete billing chain at the database level with row-by-row evidence: "
    "product and variant creation, barcode and QR identifiers, POS scan "
    "resolution, cart and checkout, payment capture, sale documents, atomic "
    "stock deduction, the append-only stock ledger, current inventory, sales "
    "history, dashboard aggregates and the seventeen reporting views. Every "
    "layer was tested against the live cloud database and against a local "
    "PostgreSQL harness that replays the exact migration chain 0001 through "
    "0014, so results reflect the same schema the production project runs.",
    "lead")))

story.extend(callout_row([
    ("353 / 353", "automated checks green (185 audit + 168 regression)"),
    ("14 / 14", "migrations applied cleanly on a fresh replay"),
    ("0", "open P0 / P1 defects"),
    ("32", "pages browser-verified, zero console errors"),
]))

story.append(para(
    "The verdict is <b>PRODUCTION READY</b> for daily shop operations at the "
    "current data scale. The billing chain is atomically safe: concurrent "
    "sales of the last unit resolve to exactly one winner, checkout is "
    "idempotent under double-click, stock can never go negative, and a failed "
    "checkout leaves no orphan records. Money arithmetic, including the "
    "exchange-difference asymmetry fixed by migration 0014, now balances "
    "end-of-day cash reconciliation to the paisa in independent recomputation. "
    "Historical integrity is preserved everywhere: cancelled, returned and "
    "exchanged documents never rewrite history, and users with activity can "
    "only be deactivated, never deleted."))

story.append(para(
    "Honesty about limits is part of this verdict. Three areas were verified "
    "by design analysis rather than live hardware testing, and they are "
    "labelled NOT TESTED rather than claimed: physical barcode scanners "
    "(keyboard-wedge behaviour is implemented and documented, but no scanner "
    "was attached to the audit environment), mobile camera QR scanning on "
    "real Android or iOS devices (the code path and its fallbacks were "
    "audited, and HTTPS plus camera-permission prerequisites are documented), "
    "and thermal printers and cash drawers (invoice and label printing use "
    "the browser print pipeline; no ESC/POS or drawer-kick integration "
    "exists, and none is claimed). In addition, the 1-crore-record "
    "performance target is supported by index-backed, bounded, paginated "
    "queries verified at 50,000 seeded sales with flat millisecond "
    "latencies, not at full production volume."))

story.append(para(
    "One operational item needs the owner's attention before the admin user "
    "management pages are used again: the Supabase service-role key on file "
    "stopped authenticating during the final verification round, which "
    "indicates the key was rotated. All customer-facing flows - login, POS, "
    "billing, inventory, reports - authenticate with the publishable key and "
    "row-level security and are unaffected. Section 16 and the checklist in "
    "Section 19 describe the two-minute replacement procedure."))

# ---------------------------------------------- 2. scope / method --------
story.extend(chapter(2, "Audit Scope, Method & Evidence Base", para(
    "The audit followed the discipline fixed at the start of the project: "
    "inspect first, never modify existing migrations, and never hide "
    "problems. Phase 6 began with a read-only architecture review - schema, "
    "row-level security policies, RPC contracts, the checkout and inventory "
    "engine, permission gates and storage rules - and produced a dependency "
    "map of the billing chain before a single fix was proposed. Only after "
    "the full evidence picture existed were fixes written, and every schema "
    "fix landed as a new additive migration (0014); migrations 0001 through "
    "0013 were not edited at any point, matching the constraint the owner "
    "set at Phase 2 and reaffirmed for Phase 6.")))

story.append(para(
    "Evidence comes from four independent sources. First, a local "
    "Supabase-compatible PostgreSQL 18 harness replays the complete "
    "migration chain on a fresh cluster, which reproduces the exact schema "
    "and role model the cloud runs; the Phase 6 suites (audit parts 1-3 and "
    "the 0014 suite) execute 185 checks against it. Second, the earlier "
    "phase regression suites - 0011, 0012 and 0013 - re-run on the same "
    "chain for 168 checks, proving that no Phase 6 fix regressed any prior "
    "behaviour. Third, browser end-to-end rounds drove the real application "
    "against the live cloud database with temporary clearly-labelled test "
    "users, walking every route, completing an actual scan-to-checkout "
    "sale, and verifying the resulting rows read-only through the service "
    "API. Fourth, read-only REST probes checked cloud deployment state and "
    "permissions without ever writing business data."))

story.append(para(
    "Test status vocabulary in this report is deliberately strict. TESTED "
    "means an automated check or a browser action produced the observed "
    "result with evidence retained in the repository. PARTIALLY TESTED "
    "means the software path was exercised but the physical device or full "
    "scale was not. NOT TESTED means no honest claim is made at all. This "
    "distinction matters most in Section 14, the hardware chapter, where "
    "claiming scanner or printer verification without equipment would be "
    "exactly the kind of dishonest reporting this audit was asked to avoid."))

# ------------------------------------------ 3. architecture / chain ------
story.extend(chapter(3, "System Architecture & the Billing Chain", para(
    "The system is a Next.js App Router application backed by a single "
    "Supabase PostgreSQL project. The browser talks to PostgREST directly "
    "with the publishable key plus the signed-in user's JWT, so row-level "
    "security and per-RPC permission gates are enforced in the database "
    "itself, not only in the UI. A small set of server-only admin routes "
    "use the service-role key. All money and stock mutations flow through "
    "SECURITY DEFINER RPCs that re-check permissions, validate business "
    "rules and keep every table write atomic.")))

story.append(para(
    "The billing chain the audit followed end-to-end is: product and "
    "variant creation with SKU, EAN-13 barcode and QR identifier; POS "
    "search or scan resolving an identifier to the exact variant; cart "
    "assembly; the checkout RPC creating the sale document, its line items "
    "and its payment records in one transaction; atomic stock deduction "
    "writing an append-only stock movement per line; the maintained "
    "stock balance per variant and location; sales history and returns; "
    "and the reporting layer that aggregates the same rows the chain "
    "wrote. Each arrow was verified with row-level evidence, for example "
    "sale INV-2026-000011 created through the browser POS during the "
    "cloud round, whose payment split, item snapshot with MRP, stock "
    "movement and audit trail were all read back and matched exactly."))

story.extend(table_block(
    "Billing-chain stages and their database guardians",
    make_table(
        ["Stage", "Tables / RPC", "Safety property verified"],
        [
            ["Product / variant", "products, product_variants, create_product_variants",
             "SKU unique case-insensitive; barcode/QR unique when present; all-or-nothing variant creation"],
            ["Identifiers", "product_variants (sku, barcode, qr_identifier)",
             "EAN-13 checksum, 20-24 in-store prefix; QR collision-safe; index-backed lookups"],
            ["POS scan", "find_variant_by_identifier RPC",
             "Exact variant resolution; fuzzy input falls back to search (Section 6)"],
            ["Checkout", "create_sale RPC",
             "One transaction: sale + items + payments; bill-level discount; credit splits"],
            ["Stock deduction", "adjust_stock inside create_sale",
             "Row-locked balance update; INSUFFICIENT_STOCK guard; never negative"],
            ["Ledger", "stock_movements",
             "Append-only (UPDATE/DELETE blocked by triggers); balance_after on every row"],
            ["History", "sales, sale_items (price snapshots)",
             "Line prices frozen at sale time; returns/exchanges never rewrite"],
            ["Reporting", "17 report RPCs + dashboard_summary",
             "Permission-gated, tz-correct windows, indexed aggregates"],
        ],
        [0.20, 0.34, 0.46]),
    "Table 1: Chain stages with the exact safety property each test round verified."))

# ----------------------------------------------- 4. migrations -----------
story.extend(chapter(4, "Migration Integrity (0001-0014)", para(
    "The database now carries fourteen migrations, all applied on the cloud "
    "project in order. The discipline the owner required - never modify or "
    "delete an applied migration, any schema change must be a new additive "
    "migration - held through Phase 6: the audit's only schema-level fix "
    "shipped as 0014_phase6_report_exchange_cash.sql, which replaces two "
    "report functions with identical signatures and adds no tables, no "
    "data and no new objects. The owner applied it in the Supabase SQL "
    "editor after this audit round, exactly as with every prior "
    "migration.")))

story.extend(table_block(
    "Migration inventory",
    make_table(
        ["Migration", "Scope", "Status"],
        [
            ["0001 core schema", "Company, profiles, roles, permissions, settings, audit log", "Cloud live"],
            ["0002 RLS policies", "Row-level security across Phase 1 tables", "Cloud live"],
            ["0003 storage", "Company assets bucket with mime/size gates", "Cloud live"],
            ["0004 products catalog", "Categories, brands, sizes, colors, products, variants + identifiers", "Cloud live"],
            ["0005 inventory stock", "Locations, balances, append-only ledger, engine RPCs", "Cloud live"],
            ["0006 product images", "product-images bucket, 2 MB, PNG/JPEG/WebP", "Cloud live"],
            ["0007 audit attribution", "user_email on catalog audit rows", "Cloud live"],
            ["0008 POS billing", "create_sale, payments, invoices, credit", "Cloud live"],
            ["0009 business ops", "Customers, suppliers, purchases, returns, exchanges, expenses", "Cloud live"],
            ["0010 active-filter fix", "manager active-filter RPC bug", "Cloud live"],
            ["0011 statement till payments", "customer_statement credits till payments", "Cloud live"],
            ["0012 reporting", "17 report RPCs + indexes (Phase 5)", "Cloud live"],
            ["0013 sales report filter", "p_payment_status argument", "Cloud live"],
            ["0014 exchange cash", "payment_report + cash_report count exchange collections", "Cloud live (applied by owner)"],
        ],
        [0.26, 0.52, 0.22], aligns=["l", "l", "c"]),
    "Table 2: Fourteen additive migrations; none of 0001-0013 was ever modified. "
    "Fresh-chain replay this session: 14/14 applied with zero errors."))

story.append(para(
    "Integrity was re-proven on the recovered workspace (Section 16): the "
    "full chain applies to a brand-new cluster without a single error, the "
    "0012 suite passes 116/116 on the 0014 state, and 0014 itself is "
    "idempotent - re-running it changes nothing. The migration README and "
    "the migrations directory in the repository remain the single source "
    "of truth for deployment order."))

# ------------------------------------------- 5. page-by-page matrix ------
story.extend(chapter(5, "Page-by-Page Audit Matrix", para(
    "Every route in the application was opened in a real browser against "
    "the live cloud database, logged in as an administrator with a "
    "temporary test account. The tour captured the final URL, the page "
    "title, any console or page error, and a horizontal-overflow "
    "measurement. All 32 routes rendered with data, zero console errors "
    "and zero page errors in the production build; the only dev-mode "
    "hydration warnings observed are React development artefacts that do "
    "not occur in the production build used for the console audit.")))

story.extend(table_block(
    "Route audit matrix (production build, live cloud data)",
    make_table(
        ["Route group", "Pages", "DB connection", "Result"],
        [
            ["Core", "Dashboard, POS, Sales history, Labels", "dashboard_summary, create_sale, sales_page, label RPCs", "WORKING"],
            ["Catalog", "Products, product detail, new product, attributes", "products_page, create_product_variants, attribute CRUD", "WORKING"],
            ["Inventory", "Inventory, stock history, locations", "stock_page, stock_history_page (keyset)", "WORKING"],
            ["Partners", "Customers, customer detail, Suppliers, supplier detail", "customer/supplier RPCs, statements", "WORKING"],
            ["Operations", "Purchases, Expenses, Payments", "purchase/expense/payment RPCs", "WORKING"],
            ["Reports", "Reports grid + 17 report pages", "17 permission-gated report RPCs", "WORKING"],
            ["Admin", "Users, Settings", "admin routes (service key), settings RPCs", "WORKING*"],
            ["Auth", "Login", "Supabase auth (publishable key)", "WORKING"],
        ],
        [0.16, 0.30, 0.36, 0.18], aligns=["l", "l", "l", "c"]),
    "Table 3: All 32 routes verified. *Users page requires a valid service-role "
    "key; see Section 16 - the on-file key was rotated."))

story.append(para(
    "Beyond rendering, the matrix checked that each page's permission gate "
    "matches its data protection: seven operation pages gained explicit "
    "server-side gates during Phase 6 so that a user without the matching "
    "permission is redirected instead of merely seeing an empty page. "
    "Underneath, the data itself was already RPC- and RLS-protected, so "
    "the fix is consistency of user experience rather than a security "
    "hole - classified P3 in the findings register."))

# --------------------------------------- 6. identifiers / POS scan -------
story.extend(chapter(6, "Identifier & POS Scan Verification", para(
    "The central identifier requirement of the audit - a barcode or QR "
    "code must resolve to the exact variant, not merely the product - is "
    "satisfied by the data model and proven by tests. Every variant "
    "carries its own SKU, optional EAN-13 barcode and optional QR "
    "identifier with unique partial indexes, and the POS scanner endpoint "
    "find_variant_by_identifier matches any of the three exactly. Test "
    "evidence: barcode 2900000000018 resolved to variant "
    "AUD-SHIRT-BLU-M (the blue shirt in size M), and QR AUDQRBLKM1 "
    "resolved to AUD-SHIRT-BLK-M; both then flowed through complete sales "
    "with exactly one stock movement each.")))

story.append(para(
    "Phase 6 hardened the scan path against a real-world mis-scan hazard "
    "the audit identified: a scanner or a fast typist can emit a partial "
    "code that fuzzy-matches an unrelated product, silently adding the "
    "wrong item to a bill. The POS now auto-adds only when the input "
    "equals a variant's barcode, QR identifier or SKU exactly; anything "
    "else - product codes, names, partial strings - falls back to the "
    "search list with a notice telling the cashier to pick the item "
    "consciously. Repeated scans of the same code increment the cart "
    "quantity on one line (three scans produce quantity three and, after "
    "checkout, one sale item), and multi-variant scanning keeps balances "
    "independent per variant."))

story.append(para(
    "The generated barcodes are valid EAN-13 with a correct checksum and "
    "the reserved in-store prefix range 20-24, so they can never collide "
    "with a future supplier barcode at the till. SKU collisions during "
    "variant creation are handled by collision-safe suffixing inside the "
    "create_product_variants RPC, which also creates all variants of a "
    "product or none at all, so a failed matrix cannot leave half-created "
    "rows behind."))

# --------------------------------- 7. stock arithmetic / concurrency -----
story.extend(chapter(7, "Stock Arithmetic, Concurrency & Idempotency", para(
    "Stock arithmetic was verified with ledger-visible evidence. A "
    "barcode sale moved the balance 10 to 9 with a SALE movement of -1 "
    "and balance_after 9; a QR sale did the same on its own variant. "
    "Out-of-stock attempts raise INSUFFICIENT_STOCK and change nothing; "
    "the exact-stock boundary (selling the last unit) succeeds once and "
    "then blocks the next attempt; negative stock is impossible unless "
    "the owner explicitly enables the documented allow_negative_stock "
    "setting. Multi-location sales deduct only the sold location's "
    "balance, and a transfer moves stock between locations as two ledger "
    "legs in one transaction with deadlock-safe ordering.")))

story.append(para(
    "Concurrency was attacked directly. Eight parallel checkouts "
    "competing for the same three remaining units let exactly three "
    "succeed and five fail cleanly, leaving the balance at exactly zero "
    "and one ledger row per successful line - the row-level lock inside "
    "adjust_stock serialises the final decrement. Double-click checkout "
    "is guarded in the UI by a disabled button plus a duplicate-submit "
    "guard, and the browser round confirmed one sale document is "
    "created; the database deliberately does not carry a client-token "
    "uniqueness constraint, a design decision the audit records as "
    "acceptable with the frontend guard verified. A checkout forced to "
    "fail mid-way leaves no orphan sale, item or payment rows because "
    "create_sale is a single transaction. Refreshing or navigating back "
    "after checkout never duplicates a bill."))

story.extend(callout_row([
    ("8 -> 3", "parallel checkouts: exactly 3 win, 5 rejected"),
    ("10 -> 9", "barcode sale with matching ledger row"),
    ("0", "negative-stock cases across all suites"),
    ("1", "sale document per double-click checkout"),
]))

# --------------------------------- 8. payments / credit / 0014 -----------
story.extend(chapter(8, "Payments, Credit & Money-Flow (incl. 0014)", para(
    "The payment matrix covers Cash, UPI, Card, Bank Transfer, Store "
    "Credit and split payments. Cash change is computed and stored "
    "exactly: receiving 2,000 on a 1,250 bill records cash_received "
    "2,000 and change 750, and the till counts 1,250 only. Split "
    "payments write one sale_payments row per method with correct "
    "amounts; credit sales record a non-credit marker row plus the "
    "credit balance so a 5,000 bill paid 2,000 upfront shows 3,000 due; "
    "customer payments later settle dues through the receipts flow, and "
    "mirrored receipts are excluded from the till so nothing is "
    "double-counted.")))

story.append(para(
    "The audit's most significant money finding - fixed by migration "
    "0014 - was an asymmetry in the reporting layer: exchange refunds "
    "(customer paid less on a downgrade swap) were counted in "
    "payment_report refunds and cash_report outflows, but exchange "
    "collections (customer paid more on an upgrade swap) were not "
    "counted as money in. A day with upgrade exchanges understated the "
    "expected drawer by exactly the collected differences, so "
    "end-of-day cash reconciliation could never balance. 0014 replaces "
    "payment_report and cash_report with versions that include an "
    "exchange_collections section, a total_exchange_in summary key and "
    "a cash_exchange_in line inside expected_cash, with byte-identical "
    "behaviour everywhere else. The local 0014 suite passes 12/12 "
    "including an independent full recomputation of expected_cash from "
    "raw tables, and the owner has applied the migration on the cloud."))

story.append(para(
    "Because the on-file service key stopped authenticating during the "
    "final verification round (Section 16), the deployed 0014 function "
    "bodies could not be re-read through the REST API from this "
    "environment. The deployment is evidenced by the owner's "
    "confirmation, by the anon-role probe showing payment_report exists "
    "and is permission-gated exactly as the migration specifies, and by "
    "the local chain equivalence. The operator checklist includes a "
    "two-minute visual confirmation on the Payments and Cash report "
    "pages, which the owner can perform from the preview in one login."))

# -------------------------- 9. purchases / returns / exchanges ------------
story.extend(chapter(9, "Purchases, Returns, Exchanges & Price History", para(
    "The purchase flow raises stock and payables atomically: a purchase "
    "of 10 units with a 3-unit supplier return nets +7 on the balance, "
    "writes matching ledger legs, and keeps the supplier's payable "
    "correct for later supplier payments. Sale returns credit the "
    "customer (cash refund out of the drawer, or Store Credit balance), "
    "restore stock, and never rewrite the original invoice: a 10-unit "
    "sale followed by a 3-unit return settles at 8 on the ledger after "
    "the restored stock passes through 10 to 7 then +1 back.")))

story.append(para(
    "Exchanges were re-verified with the exact scenario from the audit "
    "plan: a 999 rupee item swapped for a 1,199 item records a 200 "
    "difference collected from the customer with its payment method, "
    "stock moves out for the new item and back in for the returned one, "
    "and the money reports now count the 200 exactly once as an "
    "exchange collection (0014). A reverse swap refunds the difference "
    "and appears in refunds. Historical pricing is frozen by line-item "
    "snapshots: after the variant price changes, the original invoice "
    "still prints its original 999, returns and exchanges value lines "
    "at the snapshot, and the MRP column added in Phase 6 prints the "
    "line MRP captured at sale time. The invoice full-field check "
    "passed - number, date, customer, cashier, location, line detail, "
    "discounts, taxes, totals, payment split and due amount - and "
    "reprint reproduces the identical document from history."))

story.append(para(
    "Deletion and deactivation rules protect this history everywhere. "
    "Deleting a user with any ledger activity returns a clear 409 with "
    "guidance to deactivate instead; deactivation immediately removes "
    "access while every audit row and document keeps the attribution. "
    "Products and variants are soft-deactivated so old bills keep their "
    "names; the Phase 6 cleanup of its own test entities used exactly "
    "this path, deactivating the test product, variant and users "
    "without hard-deleting a single history row."))

# --------------------------------- 10. dashboard / reports / EOD ---------
story.extend(chapter(10, "Dashboard, Reports & End-of-Day Reconciliation", para(
    "The dashboard shows period-aware, permission-scoped live aggregates "
    "from the dashboard_summary RPC; the Phase 6 dashboard exact test "
    "compared every tile against direct recomputation from raw tables "
    "and matched to the paisa, and values persist correctly across "
    "refresh, logout and re-login because they are computed from the "
    "database rather than cached in the browser. The seventeen report "
    "pages all render live cloud data with their filters, CSV exports "
    "are capped at 5,000 rows to keep the browser responsive, and print "
    "styles produce clean paper output.")))

story.append(para(
    "End-of-day reconciliation is the audit's money capstone and now "
    "balances. For the simulated shop day - cash sales, UPI and card "
    "takings, a customer receipt, an expense, a cash refund, an upgrade "
    "exchange collecting cash and a downgrade exchange refunding cash - "
    "the cash report's expected_cash equalled an independent "
    "recomputation from raw tables, with opening balance carried from "
    "prior days and exchange cash included in the day's inflows. The "
    "payment report's inflows, refunds, expenses and supplier payments "
    "sections all reconcile against the same rows, and the "
    "store-credit refunds are reported separately so a paper trail "
    "exists for non-cash credits. The 0012 reporting suite (116 "
    "checks) re-passed on the 0014 state, confirming no reporting "
    "behaviour regressed."))

# -------------------------------------------- 11. security audit ---------
story.extend(chapter(11, "Security & Access Control Audit", para(
    "Security was probed at the database level, not only through the UI. "
    "Anonymous REST requests were fired directly against every sensitive "
    "table and RPC: they return permission denied, because grants were "
    "revoked from the anon role and row-level security plus table ACLs "
    "sit in front of every read. Authenticated low-privilege sessions "
    "(a cashier) were simulated with their JWT claim set, attempting "
    "product writes, stock writes, report reads and audit reads - all "
    "correctly denied by the RPC permission gates, with audit_logs "
    "readable only through the gated audit_page RPC, which is a hard "
    "boundary between browsing data and reading the audit trail.")))

story.append(para(
    "Ghost-user attempts (JWT claims for a user id that does not exist) "
    "are rejected, deactivated users lose access, and role changes take "
    "effect immediately because permissions are checked per request. "
    "Public sign-up is disabled at the Supabase project level, which the "
    "audit verified and which matters structurally: a database trigger "
    "gives every newly created auth user a cashier-level profile, so an "
    "open sign-up would hand strangers till access. The audit recommends "
    "keeping sign-up disabled permanently and creating staff only through "
    "the admin user management page. The service-role key never ships to "
    "the browser - it is read only by server routes from the environment "
    "file, which is git-ignored and never committed."))

story.append(para(
    "Storage rules were part of the review: the product-images bucket "
    "accepts only PNG, JPEG and WebP up to 2 MB (SVG is excluded, which "
    "closes an XSS vector), and write policies are gated on the "
    "manage_products permission. Admin API routes that use the "
    "service key are server-only and were exercised through the "
    "application during the browser rounds."))

# -------------------------------------------- 12. db integrity -----------
story.extend(chapter(12, "Database Integrity Audit", para(
    "A dedicated integrity pass swept the database for structural damage "
    "of the kinds that silently corrupt business reporting: orphan rows, "
    "duplicates and impossible values. Every sale item joins to a sale "
    "and a variant; every payment joins to a sale; every stock movement "
    "joins to a variant and a location; every ledger chain was replayed "
    "from opening balances and the computed running total matched the "
    "maintained stock_balances quantity for every variant at every "
    "location. No duplicate SKUs, barcodes or QR identifiers exist "
    "(the unique indexes would have rejected them at insert). No "
    "negative stock rows and no negative money rows were found, and the "
    "paid-plus-due invariant holds on every bill.")))

story.append(para(
    "The append-only ledger is protected by triggers that block UPDATE "
    "and DELETE on stock_movements, and balance rows can only change "
    "through the engine's GUC-guarded path, so even a direct SQL "
    "connection cannot quietly rewrite history. Idempotency was checked "
    "structurally as well: re-applying migrations 0012 and 0014 changes "
    "nothing, and duplicate submission from the UI cannot create a "
    "second bill because checkout guards state before the RPC call. The "
    "integrity results held identically on the fresh replay this "
    "session, which is itself evidence that the repository state and "
    "the cloud schema agree."))

# -------------------------------------------- 13. performance ------------
story.extend(chapter(13, "Performance & Scale Readiness", para(
    "The audit's scale question - will this survive 1 crore (10 million) "
    "rows - is answered with design evidence plus a seeded load test, "
    "not with a claim. Structurally, every identifier lookup is "
    "index-backed (the scanner path uses the same unique indexes that "
    "enforce correctness), every list page paginates at the database "
    "(LIMIT/OFFSET or keyset cursors on the movement history), every "
    "report filters by an indexed date window and aggregates inside "
    "PostgreSQL, and CSV exports are capped at 5,000 rows so no report "
    "can drag an entire table into the browser. No full-table fetch "
    "path was found in the audited queries.")))

story.append(para(
    "The load test seeded 50,000 sales with 150,000 line items, 60,000 "
    "payments and 4,000 variants into the local harness and ran every "
    "report RPC against the dataset: all completed in 2 to 75 "
    "milliseconds with bitmap index scans confirmed on the date-windowed "
    "paths. Extrapolating honestly, index-backed point lookups and "
    "windowed aggregates do not degrade linearly with table size, so "
    "the design remains sound at 1 crore rows; nevertheless, this is "
    "PARTIALLY TESTED scale evidence, because no environment in this "
    "audit held a crore of real rows. The report layer's date-window "
    "indexes from 0012 are the load-bearing component, and they are "
    "verified live on the cloud."))

story.extend(table_block(
    "Scale-safety mechanisms verified",
    make_table(
        ["Mechanism", "Where", "Status"],
        [
            ["Unique indexes on SKU / barcode / QR", "product_variants (0004)", "TESTED"],
            ["Keyset pagination on movement history", "stock_history_page (0005)", "TESTED"],
            ["DB-side filter / sort / pagination on lists", "products_page, stock_page, sales pages", "TESTED"],
            ["Indexed date windows on reports", "0012 index set", "TESTED"],
            ["Aggregation inside PostgreSQL", "17 report RPCs", "TESTED"],
            ["Export cap 5,000 rows", "report CSV export", "TESTED"],
            ["Behaviour at 1 crore live rows", "production dataset", "NOT TESTED (design-safe)"],
        ],
        [0.38, 0.34, 0.28], aligns=["l", "l", "c"]),
    "Table 4: Every query path is bounded; the only untested item is full "
    "production volume itself."))

# -------------------------------------------- 14. hardware (honest) ------
story.extend(chapter(14, "Hardware & Mobile - Honest Status", para(
    "No physical scanner, printer, cash drawer or mobile device was "
    "attached to this audit environment, so this section reports "
    "implementation facts and explicitly marks what was not tested. "
    "The barcode scanner integration is keyboard-wedge by design: a USB "
    "or Bluetooth scanner types the code into the focused scanner "
    "input and sends Enter, which the POS treats exactly like manual "
    "entry followed by the scan resolution path - including the "
    "exact-identifier gate and the fallback-to-search safety. The "
    "scanner input is focused by default on the POS page, so a "
    "wedge scanner works with zero configuration.")))

story.append(para(
    "Camera QR scanning uses the browser BarcodeDetector API with the "
    "rear camera; when a browser lacks the API or camera access, the "
    "dialog says so plainly - 'Camera QR scanning is not supported in "
    "this browser. Use the barcode scanner input or search instead.' - "
    "and the camera is never a dependency of billing. This message "
    "appears in browsers without the API (notably some desktop "
    "browsers and in-app webviews); the audited fallbacks are the "
    "wedge-scanner input, manual entry and product search. Real-device "
    "verification on Android Chrome and iPhone Safari over HTTPS, "
    "including the camera-permission prompt, remains NOT TESTED and "
    "is on the operator checklist. Printing uses the browser print "
    "pipeline for invoices (A4) and labels (template sizes for thermal "
    "rolls); a thermal printer connected to the OS prints through the "
    "browser dialog, but no direct ESC/POS integration exists and none "
    "is claimed. The cash drawer has no integration at all - it is "
    "opened manually, and the audit states this plainly."))

story.extend(table_block(
    "Hardware and mobile capability matrix",
    make_table(
        ["Capability", "Implementation", "Status"],
        [
            ["USB/Bluetooth wedge scanner", "Keyboard input + Enter in scanner field; exact-identifier gate", "TESTED (software path); hardware NOT TESTED"],
            ["Camera QR (mobile)", "BarcodeDetector API + fallback message + manual paths", "PARTIALLY TESTED (no real device)"],
            ["Invoice printing (A4)", "Browser print with print CSS, MRP column", "TESTED (browser print)"],
            ["Label printing", "Template sizes + browser print; deep links resolve", "TESTED (browser print)"],
            ["Thermal printer (ESC/POS)", "Not integrated; prints via browser dialog", "NOT TESTED / not integrated"],
            ["Cash drawer kick", "Not integrated", "Not integrated (stated honestly)"],
            ["Offline behaviour", "Cloud-only: no offline mode", "By design (documented)"],
        ],
        [0.24, 0.44, 0.32], aligns=["l", "l", "l"]),
    "Table 5: No hardware claim is made beyond what was actually exercised."))

# --------------------------------------- 15. browser / console -----------
story.extend(chapter(15, "Browser, Console & Responsive Audit", para(
    "The production build was served and every route was visited twice "
    "while capturing console output, page errors and layout overflow. "
    "The result was zero unexpected console errors and zero page errors "
    "across all 32 routes; the only tolerated lines are benign "
    "development-mode hydration notices that do not appear in the "
    "production build, which was the build under test. Network calls "
    "were inspected during the POS flow: no failing requests, no "
    "duplicate checkout calls on double-click, and a failed payment "
    "never produces a success toast because the UI only acknowledges "
    "the transaction the database committed.")))

story.append(para(
    "Responsiveness was measured at 320, 375, 768, 1280, 1920 and 2560 "
    "pixels wide: scrollWidth equalled the viewport on every audited "
    "page, meaning zero horizontal overflow, including the POS at "
    "phone width where the full scan-search-checkout flow was walked "
    "through at 375 pixels. Deep links were exercised directly - "
    "opening labels with a variant query parameter now resolves the "
    "variant (previously a silent no-op, fixed in Phase 6), and "
    "report URLs with filters render correctly after a hard refresh. "
    "The back and forward buttons never re-submit a checkout."))

# ------------------------------------ 16. workspace recovery -------------
story.extend(chapter(16, "Workspace Recovery & Environment State", para(
    "Between the audit rounds and this final report, the development "
    "sandbox was reset and the local working copy of the codebase was "
    "wiped - which is why the code and preview views temporarily "
    "disappeared from the workspace. Recovery was clean and verified: "
    "the repository was re-cloned from GitHub (the Phase 6 audit commit "
    "is the current HEAD), the environment file was recreated from the "
    "project's credentials, dependencies were reinstalled, and the "
    "preview server was brought back up with a passing health check "
    "against the cloud database. Nothing in the cloud was touched by "
    "the reset.")))

story.append(para(
    "To prove the recovered code is exactly the audited code, the full "
    "local verification battery was re-run on the fresh sandbox: the "
    "fourteen migrations applied cleanly to a new cluster, the Phase 6 "
    "audit suites passed 185/185, and the regression suites passed "
    "168/168 - numbers identical to the original audit run. This "
    "re-verification doubles as the final integrity check of the "
    "delivered repository state."))

story.append(para(
    "One finding emerged during recovery: the Supabase service-role "
    "key previously on file now returns 'Invalid API key' against the "
    "project's REST API, while the publishable key still authenticates "
    "correctly. This means the key was rotated (or replaced) at some "
    "point. The impact is narrow: every browser-facing flow works "
    "because it uses the publishable key with row-level security, but "
    "the server-only admin routes - user management - cannot reach "
    "the admin API until the environment file carries the current "
    "service key. The fix is a two-minute edit documented in the "
    "operator checklist: copy the new service key from the Supabase "
    "dashboard into .env.local and restart the server. If the key was "
    "not rotated intentionally, regenerating it from the dashboard is "
    "still safe and takes the same two minutes."))

# ---------------------------------------- 17. findings register ----------
story.extend(chapter(17, "Findings & Fixes Register (P0-P3)", para(
    "The register below is the complete list of real defects the audit "
    "found, their severity, the fix shipped, and the retest evidence. "
    "No P0 (data loss / money loss / security hole) defect was open at "
    "any point in Phase 6. The single P1 was the exchange-cash "
    "reporting asymmetry, which never touched stored money - it "
    "mis-reported money that had been correctly collected - but would "
    "have made daily drawer reconciliation impossible to balance, so "
    "it was fixed before the verdict. Everything else is P2/P3 "
    "quality and consistency work, all fixed and retested in this "
    "phase.")))

story.extend(table_block(
    "Findings and fixes",
    make_table(
        ["ID", "Sev", "Finding", "Fix", "Retest"],
        [
            ["F-01", "P1", "Exchange collections missing from payment_report inflows and cash_report expected_cash; EOD drawer could never balance on upgrade-exchange days", "Migration 0014 (additive, owner-applied)", "0014 suite 12/12 incl. independent recomputation"],
            ["F-02", "P2", "POS auto-added items on partial/fuzzy codes - mis-scan could bill the wrong product", "Scan gate: only exact variant identifiers auto-add; everything else falls back to search", "audit part 1 + browser POS round"],
            ["F-03", "P2", "Labels ?variant= deep link was a silent no-op", "Deep link resolves the variant by id", "browser deep-link round"],
            ["F-04", "P3", "Invoice lacked the MRP column", "MRP column printed from line snapshots", "invoice full-field check"],
            ["F-05", "P3", "Seven operation pages lacked explicit permission gates (UX inconsistency; data was already protected)", "Server-side gates on customers, suppliers, payments, purchases, expenses", "page tour + gate probes"],
            ["F-06", "P3", "Settings carried nine never-consumed fields; print-size options mismatched templates", "Dead fields removed; options aligned", "settings round"],
            ["F-07", "P3", "Stock-history date filter ignored store timezone", "Filter pinned to IST store timezone", "audit part 3"],
            ["F-08", "P3", "Checkout dialog kept stale totals when the cart changed", "Dialog resets on total change", "browser checkout round"],
            ["F-09", "P3", "Deleting a user with history failed unclearly", "Clear 409 with deactivate guidance", "admin route test"],
        ],
        [0.07, 0.06, 0.37, 0.28, 0.22], aligns=["c", "c", "l", "l", "l"]),
    "Table 6: Every fix landed in Phase 6 and was retested; open items are "
    "operational, not defects (see Sections 16 and 19)."))

story.append(para(
    "Two non-defect design decisions are recorded for transparency. "
    "First, checkout idempotency is enforced in the UI layer rather "
    "than by a database client-token constraint; the audit verified the "
    "guard works in practice (double-click produced exactly one sale) "
    "and a forced failure leaves no partial records, so the design is "
    "accepted. Second, any newly created auth user receives a "
    "cashier-level profile through a database trigger; combined with "
    "disabled public sign-up this is safe, and it is the reason "
    "sign-up must remain disabled."))

# ---------------------------------------- 18. test matrix ----------------
story.extend(chapter(18, "Test Matrix & Coverage Summary", para(
    "The table maps each audit plan area to the suite that covered it, "
    "the check count, and the honest status. The three automated "
    "suites plus the 0014 suite and the three regression suites were "
    "re-run end-to-end on the recovered workspace for this report, "
    "so every number below was reproduced in the final state, not "
    "copied from an earlier session.")))

story.extend(table_block(
    "Coverage by audit area",
    make_table(
        ["Audit area", "Suite", "Checks", "Result"],
        [
            ["Identifiers, scan-to-variant, sale chain, stock edge cases, concurrency (plan sections 6-16)", "test-audit1", "73", "PASS 73/73"],
            ["Payments, credit, purchases, returns, exchanges, price history, delete/deactivate (17-25, 39)", "test-audit2", "52", "PASS 52/52"],
            ["Dashboard exact test, EOD reconciliation, integrity, RLS, indexes (4, 37, 43-44, 50-51)", "test-audit3", "48", "PASS 48/48"],
            ["0014 exchange-cash reporting fix", "test-0014", "12", "PASS 12/12"],
            ["Customer statement till-payment regression", "test-0011", "27", "PASS 27/27"],
            ["Full reporting layer regression", "test-0012", "116", "PASS 116/116"],
            ["Sales report payment-status filter regression", "test-0013", "25", "PASS 25/25"],
            ["Page tour, POS browser flow, double-click, mobile 375px, console", "browser E2E", "32 routes", "PASS, zero console errors"],
            ["Cloud deployment probes (read-only)", "REST probes", "-", "PASS until key rotation"],
            ["Hardware scanner / real-device camera / thermal printer / cash drawer", "manual", "-", "NOT TESTED (no hardware)"],
        ],
        [0.44, 0.15, 0.13, 0.28], aligns=["l", "l", "c", "l"]),
    "Table 7: 353 automated checks green (185 + 168), all reproduced on the "
    "final recovered workspace."))

# ------------------------------------- 19. operator checklist ------------
story.extend(chapter(19, "Outstanding Items & Operator Checklist", para(
    "Phase 6 stops here per the audit plan: audit, fix, verify, report, "
    "stop. What remains below is a short operator checklist for the "
    "owner - five-minute items that either close the two evidence gaps "
    "this environment cannot close, or keep the system healthy. None "
    "of them is a defect; all of them are usage and hygiene items "
    "documented so they are not forgotten.")))

story.extend(table_block(
    "Operator checklist",
    make_table(
        ["#", "Item", "How", "Why"],
        [
            ["1", "Confirm 0014 live on the reports", "Open preview, log in, Reports - Payments: an 'Exchange collections' section appears; Reports - Cash: a 'Cash exchange in' line appears and expected cash looks right", "Closes the one cloud-side verification this environment could not re-read after the key rotation"],
            ["2", "Replace the rotated service key", "Supabase dashboard - Settings - API, copy the current service key into .env.local (SUPABASE_SERVICE_ROLE_KEY), restart the server", "Restores the admin user-management routes; browser flows are unaffected"],
            ["3", "Keep public sign-up disabled", "Supabase dashboard - Authentication - Providers: leave Sign-up disabled", "Every new auth user gains cashier rights by design; staff are created only from the Users page"],
            ["4", "Real-device camera QR check", "Open the preview over HTTPS on Android Chrome and iPhone Safari; try the QR dialog; if the unsupported message shows, use the scanner input or search", "Turns PARTIALLY TESTED into TESTED with a two-minute check"],
            ["5", "Attach a wedge scanner for a day", "Any USB/Bluetooth keyboard-wedge scanner into the POS scanner field", "Confirms the hardware path on real equipment"],
            ["6", "Daily backup awareness", "Supabase automated daily backups (paid tier) or scheduled pg_dump; verify a restore once", "The audit verified correctness, not disaster recovery"],
        ],
        [0.05, 0.24, 0.42, 0.29], aligns=["c", "l", "l", "l"]),
    "Table 8: Five minutes of owner action closes every open item."))

story.append(para(
    "Beyond the checklist, two standing recommendations. First, adopt a "
    "simple end-of-day habit: open Reports - Cash, compare expected "
    "cash with the drawer, and investigate any difference the same "
    "day - the ledger makes every paisa traceable, which only helps "
    "if the habit exists. Second, before any future bulk import of "
    "products (Excel or CSV), re-run the identifier uniqueness rules "
    "the import path enforces; the database constraints make a bad "
    "import fail safely, but cleaning up a half-import is still work "
    "that a dry-run on a few rows avoids."))

# ------------------------------------- 20. final recommendation ----------
VERDICT_STATS = [
    ("PRODUCTION READY", "final verdict - billing, stock, money, security"),
    ("353 / 353", "automated checks green, reproduced on final state"),
    ("0", "open P0 / P1 defects"),
    ("14 / 14", "migrations live, chain replayed clean"),
]

story.extend(chapter(20, "Final Recommendation & Sign-Off", para(
    "Recommendation: <b>PRODUCTION READY</b>. The billing chain is "
    "verified end-to-end with row-level evidence, atomic under "
    "concurrency, honest under failure, and reconcilable to the "
    "paisa at the end of the day. Security is enforced in the "
    "database with sign-up closed, the audit trail attributes every "
    "change, and history cannot be rewritten by accident or by "
    "deletion. All 353 automated checks are green and were "
    "reproduced on the final delivered state of the code, and the "
    "page-by-page browser tour found zero console errors on every "
    "route the business uses daily.", "lead")))

story.append(para(
    "The verdict carries the explicit, honest caveats recorded "
    "throughout this report: no physical scanner, printer, cash "
    "drawer or real mobile device participated in the audit "
    "(software paths tested, hardware NOT TESTED); full 1-crore "
    "volume is design-verified and load-verified at 50,000 sales, "
    "not live-verified; and the two-minute operator items - the "
    "service key replacement and the visual 0014 confirmation - "
    "remain on the owner's checklist. None of these caveats "
    "touches the correctness of a single bill, and each is closed "
    "by ordinary usage rather than engineering."))

story.extend(callout_row(VERDICT_STATS))

story.append(para(
    "This concludes Phase 6 as instructed: audit, fix, verify, "
    "report, stop. No further phase is started by this report. The "
    "system is handed over for daily shop use with the evidence, "
    "the fixes and the honest limits all on the table."))

# ------------------------------------------------------------- build -----
doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
print("BUILD OK:", OUT)
